SELECT PT_NAME, PT_NO, GEND_CD, AGE, COALESCE(TLNO, 'NONE') AS TLNO -- NULL을 대체하는 문자열
FROM PATIENT
WHERE AGE <= 12 and GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME ASC; -- 내림차순 후 같으면 오름차순


SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD, '%Y-%m-%d') AS HIRE_DATE -- DATE_FORMAT
FROM DOCTOR
WHERE MCDP_CD = 'CS' OR MCDP_CD = 'GS'
ORDER BY HIRE_YMD DESC, DR_NAME ASC;


SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF, ICECREAM_INFO
WHERE TOTAL_ORDER >= 3000 and INGREDIENT_TYPE = 'fruit_based'
    and FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR -- JOIN
ORDER BY TOTAL_ORDER DESC


SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
FROM FOOD_FACTORY
WHERE ADDRESS LIKE '강원도%' -- %를 쓸라면 LIKE를 써야댐
ORDER BY FACTORY_ID ASC


SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d')
AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE DATE_FORMAT(DATE_OF_BIRTH, '%m') = '03' and TLNO IS NOT NULL and GENDER = 'W'
-- DATE에서 '월'만 꺼내기, NULL인거 출력 안하기
ORDER BY MEMBER_ID ASC


SELECT ROUND(AVG(DAILY_FEE), 0) AS AVERAGE_FEE -- 평균값 구한 후 일의 자리 까지 반올림
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = 'SUV'


SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION != 'Aged' -- 특정 값이 아닌 것
ORDER BY ANIMAL_ID ASC


SELECT NAME 
FROM ANIMAL_INS
ORDER BY DATETIME ASC
LIMIT 1 -- 상위 n개의 레코드 출력


-- Union 사용
-- 두 테이블을 양식을 동일하게 하고 합치기
SELECT * 
FROM (
    SELECT 
        DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE,
        PRODUCT_ID,
        USER_ID,
        SALES_AMOUNT
        FROM ONLINE_SALE
        WHERE date_format(sales_date, "%m") = '03'
    UNION
    SELECT 
        DATE_FORMAT(SALES_DATE,'%Y-%m-%d')AS SALES_DATE ,
        PRODUCT_ID,
        NULL AS USER_ID, -- NULL값을 넣어줘야함
        SALES_AMOUNT
        FROM OFFLINE_SALE
        WHERE date_format(sales_date, "%m") = '03'
    ) as a
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;


